version: "3.8"

services:
  db:
    image: mysql
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: "mydb"
    volumes:
      - db-data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db-data:
